title: UTSA INCH Lab
author: Denver Brown
description: Infant Child & Youth Health lab at The University of Texas at San Antonio
#theme: just-the-docs
remote_theme: pmarsceill/jtd-remote

url: https://inchlab-utsa.github.io

aux_links:
  INCH lab Repository: https://github.com/inchlab-utsa
  
aux_links_new_tab: true


logo: https://raw.githubusercontent.com/inchlab-utsa/inchlab-utsa.github.io/main/imgs/INCH.png

search_enabled: false

heading_anchors: false

color_scheme: dark


back_to_top: true
back_to_top_text: "Back to top"


footer_content: "Copyright &copy; 2022 Denver Brown </a>"




