title: INCH lab at UTSA
description: The INCH Lab was established in 2013 to better understand the mental & physical health of children & youth
theme: just-the-docs

url: https://inchlab-utsa.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
