title: UTSA INCH Lab
author: Denver Brown
description: INfant Child & youth Health lab at The University of Texas at San Antonio  sdf
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

url: https://inchlab-utsa.github.io

aux_links:
  INCH lab Repository: https://github.com/inchlab-utsa
  
aux_links_new_tab: true


logo: imgs/INCH.png
favicon_ico: imgs/favicon.ico
 
 
search_enabled: false

heading_anchors: false

color_scheme: "light"


back_to_top: true
back_to_top_text: "Back to top"


footer_content: "Copyright &copy; 2022 Denver Brown </a>"




