title: UTSA INCH Lab
author: Denver Brown
description: Infant Child & Youth Health lab at The University of Texas at San Antonio
theme: just-the-docs

url: https://inchlab-utsa.github.io

aux_links:
  INCH lab Repository: https://github.com/inchlab-utsa



logo: https://github.com/inchlab-utsa/inchlab-utsa.github.io/blob/main/imgs/INCH.png


